trigger: 'none' # will disable CI builds entirely
# - master
pr: none
# - master
# - releases/*

jobs:
- job: WebApp
  displayName: 'Build Web App'
  pool:
    vmImage: 'windows-2019'
  variables:
    BuildConfiguration: release
  
  steps:
  
  - task: UseDotNet@2
    displayName: Install .NET 8 sdk
    inputs:
      packageType: sdk
      version: 8.0.x
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: 'WebApplication CICD.csproj'
  
  - powershell: |
     $paths = Get-ChildItem -include *.csproj -Recurse
     foreach($pathobject in $paths) 
     {
         $path = $pathobject.fullname
         $doc = New-Object System.Xml.XmlDocument
         $doc.Load($path)
         $child = $doc.CreateElement("ProjectGuid")
         $child.InnerText = [guid]::NewGuid().ToString().ToUpper()
         $node = $doc.SelectSingleNode("//Project/PropertyGroup")
         $node.AppendChild($child)
         $doc.Save($path)
     }
    workingDirectory: WebApp
    displayName: 'PS : Add Project GUID'
    enabled: false
  
  - task: SonarCloudPrepare@1
    displayName: 'Prepare analysis on SonarCloud'
    inputs:
      SonarCloud: SonarCloud
      organization: houssemdellai
      projectKey: WebAppWithDatabaseDemo
  
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: 'WebApplication CICD.csproj'
      arguments: '--configuration $(BuildConfiguration)'
  
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: '**/*UnitTest*.csproj'
      arguments: '--configuration $(BuildConfiguration)'
  
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: True
      arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
      zipAfterPublish: True
  
  - task: SonarCloudAnalyze@1
    displayName: 'Run Code Analysis'
  
  - task: SonarCloudPublish@1
    displayName: 'Publish Quality Gate Result'
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact (WebApp.zip)'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'

